# Generated by Django 6.0.4 on 2026-05-04 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('Event_Name', models.CharField(help_text='Ex: Formation Django, Tournoi de football, etc.', max_length=200, verbose_name="Nom de l'événement")),
                ('type', models.CharField(choices=[('CULTURE', 'Culture'), ('JEUNESSE', 'Jeunesse'), ('FORMATION', 'Formation'), ('EVENEMENT', 'Événement'), ('ART', 'Art'), ('SPORT', 'Sport'), ('SOLIDARITE', 'Solidarité'), ('SANTE', 'Santé'), ('CITOYENNETE', 'Citoyenneté'), ('AUTRE', 'Autre')], help_text="Catégorie de l'événement", max_length=20, verbose_name='Type')),
                ('Duration', models.DurationField(help_text="Durée totale de l'événement (ex: 2 heures, 1 jour, etc.)", verbose_name='Durée')),
                ('Cost', models.DecimalField(decimal_places=2, default=0, help_text='Prix de participation (0 = gratuit)', max_digits=10, verbose_name='Coût')),
                ('Volunteers', models.IntegerField(default=0, help_text='Combien de bénévoles sont requis pour cet événement', verbose_name='Bénévoles nécessaires')),
                ('description', models.TextField(help_text="Description détaillée de l'événement", verbose_name='Description')),
                ('start_date', models.DateTimeField(help_text="Date et heure de début de l'événement", verbose_name='Date de début')),
                ('end_date', models.DateTimeField(help_text="Date et heure de fin de l'événement", verbose_name='Date de fin')),
                ('location', models.CharField(help_text='Nom du lieu (ex: Salle polyvalente, Stade, etc.)', max_length=200, verbose_name='Lieu')),
                ('city', models.CharField(help_text="Ville où se déroule l'événement", max_length=100, verbose_name='Ville')),
                ('created_by', models.ForeignKey(help_text='Administrateur qui a créé cet événement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Photo de l'événement", upload_to='events/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text="Description optionnelle de l'image", max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = première)", verbose_name='Ordre')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('event', models.ForeignKey(help_text="L'événement auquel appartient cette image", on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': "Photo d'événement",
                'verbose_name_plural': "Photos d'événements",
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type'], name='events_even_type_654a97_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city'], name='events_even_city_533bd7_idx'),
        ),
    ]
