# Generated by Django 6.0.4 on 2026-05-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_actual_participants_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.TextField(blank=True, help_text='Liste des invités séparés par des virgules', verbose_name='Invités / Guests'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text="Image principale de l'événement", null=True, upload_to='events/posters/', verbose_name='Poster principal'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Heure de début (ex: 14:30)', null=True, verbose_name='Heure de début'),
        ),
    ]
