# Generated by Django 6.0.4 on 2026-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_guests_event_poster_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text="Image principale de l'événement (affiche)", null=True, upload_to='events/posters/', verbose_name='Poster principal'),
        ),
    ]
