# Generated by Django 6.0.4 on 2026-05-06 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('events', '0004_event_guests_event_poster_event_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_featured', '-start_date'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_created_da46df_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='announcemen_expires_854584_idx',
        ),
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text="Date et heure de fin de l'annonce (ex: 20/05/2025 18:00)", null=True, verbose_name='Date et heure de fin'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, default='', help_text="Lieu de l'événement ou de l'annonce", max_length=200, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text="Date et heure de début de l'annonce (ex: 15/05/2025 14:30)", null=True, verbose_name='Date et heure de début'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Lien optionnel vers un événement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='events.event', verbose_name='Événement lié'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Alias pour date de fin', null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['start_date'], name='announcemen_start_d_dfc12a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['end_date'], name='announcemen_end_dat_a7628d_idx'),
        ),
    ]
