# Generated by Django 6.0.4 on 2026-05-04 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_max_places_event_status_alter_event_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(help_text="Titre accrocheur de l'annonce", max_length=200, verbose_name='Titre')),
                ('content', models.TextField(help_text="Contenu détaillé de l'annonce", verbose_name='Contenu')),
                ('type', models.CharField(choices=[('NEWS', 'Actualité'), ('ALERT', 'Alerte'), ('PROMO', 'Promotion'), ('INFO', 'Information'), ('EVENT', 'Événement')], default='NEWS', help_text="Type d'annonce (détermine l'apparence)", max_length=20, verbose_name='Type')),
                ('image', models.ImageField(help_text="Image de l'annonce (obligatoire pour l'affichage visuel)", upload_to='announcements/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, help_text="Cochez pour afficher l'annonce sur le site", verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Les annonces à la une apparaissent en premier', verbose_name='À la une')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Si renseigné, l'annonce disparaît automatiquement après cette date", null=True, verbose_name="Date d'expiration")),
                ('author', models.ForeignKey(help_text="Administrateur qui a créé l'annonce", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('event', models.ForeignKey(blank=True, help_text="Lien optionnel vers un événement (affiche un bouton 'Participer')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='events.event', verbose_name='Événement lié')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='announcemen_is_acti_a26055_idx'), models.Index(fields=['is_featured'], name='announcemen_is_feat_1de2b9_idx'), models.Index(fields=['-created_at'], name='announcemen_created_da46df_idx'), models.Index(fields=['expires_at'], name='announcemen_expires_854584_idx')],
            },
        ),
    ]
