# Generated by Django 6.0.4 on 2026-05-04 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_max_places_event_status_alter_event_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé')], default='PENDING', help_text="Statut de l'inscription", max_length=20, verbose_name='Statut')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text="Date à laquelle l'inscription a été confirmée", null=True, verbose_name='Date de confirmation')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text="Date à laquelle l'inscription a été annulée", null=True, verbose_name="Date d'annulation")),
                ('notes', models.TextField(blank=True, help_text='Notes optionnelles (ex: besoins spécifiques, commentaires)', verbose_name='Notes')),
                ('event', models.ForeignKey(help_text="L'événement auquel on s'inscrit", on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Événement')),
                ('user', models.ForeignKey(help_text="L'utilisateur qui s'inscrit", on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event'], name='registratio_user_id_afd0d9_idx'), models.Index(fields=['status'], name='registratio_status_42419d_idx'), models.Index(fields=['created_at'], name='registratio_created_a226d9_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
