# Generated by Django 6.0.4 on 2026-05-06 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse complète', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date de naissance du membre (JJ/MM/AAAA)', null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, help_text="Numéro de la carte d'identité", max_length=20, verbose_name="CIN (Carte d'Identité Nationale)"),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER_STANDARD', 'Membre Standard'), ('MEMBER_BUREAU', 'Membre de Bureau')], default='MEMBER_STANDARD', max_length=20, verbose_name='Rôle'),
        ),
    ]
