# Generated by Django 6.0.4 on 2026-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date', models.DateField(unique=True)),
                ('new_members', models.IntegerField(default=0)),
                ('total_members', models.IntegerField(default=0)),
                ('new_events', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('published_events', models.IntegerField(default=0)),
                ('new_registrations', models.IntegerField(default=0)),
                ('total_registrations', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Statistique journalière',
                'verbose_name_plural': 'Statistiques journalières',
                'ordering': ['-date'],
            },
        ),
    ]
