# Generated by Django 6.0.4 on 2026-05-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(help_text='Nom complet du partenaire ou sponsor', max_length=200, verbose_name='Nom du partenaire')),
                ('type', models.CharField(choices=[('SPONSOR', 'Sponsor'), ('MEDIA', 'Média'), ('INSTITUTION', 'Institution'), ('ASSOCIATION', 'Association'), ('COMPANY', 'Entreprise'), ('OTHER', 'Autre')], default='OTHER', help_text='Catégorie du partenaire', max_length=20, verbose_name='Type')),
                ('logo', models.ImageField(help_text='Logo du partenaire (format PNG ou JPEG recommandé)', upload_to='partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, help_text='URL du site web du partenaire (ex: https://www.exemple.com)', verbose_name='Site web')),
                ('email', models.EmailField(blank=True, help_text='Email de contact pour le partenaire', max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone du partenaire', max_length=20, verbose_name='Téléphone')),
                ('description', models.TextField(blank=True, help_text='Description courte du partenaire et de son rôle', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Cochez pour afficher ce partenaire sur le site', verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, help_text='Les partenaires avec un ordre plus petit apparaissent en premier', verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='partners_pa_is_acti_0df372_idx'), models.Index(fields=['type'], name='partners_pa_type_999000_idx'), models.Index(fields=['order'], name='partners_pa_order_3e56bf_idx')],
            },
        ),
    ]
