# Generated by Django 6.0.4 on 2026-05-04 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_places',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de places'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('CANCELLED', 'Annulé'), ('COMPLET', 'Complet')], default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Duration',
            field=models.DurationField(verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_Name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'événement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='Volunteers',
            field=models.IntegerField(default=0, verbose_name='Bénévoles nécessaires'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('CULTURE', 'Culture'), ('JEUNESSE', 'Jeunesse'), ('FORMATION', 'Formation'), ('EVENEMENT', 'Événement'), ('ART', 'Art'), ('SPORT', 'Sport'), ('SOLIDARITE', 'Solidarité'), ('SANTE', 'Santé'), ('CITOYENNETE', 'Citoyenneté'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='events/gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
    ]
