# Generated by Django 6.0.4 on 2026-05-05 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_max_places_event_status_alter_event_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_participants_count',
            field=models.IntegerField(blank=True, help_text="Nombre réel de participants (après l'événement)", null=True, verbose_name='Nombre réel de participants'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_social_impact',
            field=models.FloatField(blank=True, help_text="Évalué après l'événement par l'admin (0-1)", null=True, verbose_name='Impact social réel'),
        ),
        migrations.AddField(
            model_name='event',
            name='ai_priority_score',
            field=models.FloatField(blank=True, help_text="Score calculé par l'IA (0-1) pour recommander l'événement", null=True, verbose_name='Score de priorité IA'),
        ),
        migrations.AddField(
            model_name='event',
            name='ai_updated_at',
            field=models.DateTimeField(blank=True, help_text="Date du dernier calcul par l'IA", null=True, verbose_name='Dernière mise à jour IA'),
        ),
        migrations.AddField(
            model_name='event',
            name='member_satisfaction',
            field=models.FloatField(blank=True, help_text='Note moyenne de satisfaction (0-1)', null=True, verbose_name='Satisfaction membres'),
        ),
        migrations.AddField(
            model_name='event',
            name='predicted_social_impact',
            field=models.FloatField(default=0.7, help_text="Valeur par défaut basée sur le type d'événement (0-1)", verbose_name='Impact social prédit'),
        ),
        migrations.AddField(
            model_name='event',
            name='used_for_ai_training',
            field=models.BooleanField(default=False, help_text="True si cet événement a déjà été utilisé pour ré-entraîner l'IA", verbose_name='Utilisé pour entraînement IA'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['used_for_ai_training'], name='events_even_used_fo_1f538c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['ai_priority_score'], name='events_even_ai_prio_80c4bc_idx'),
        ),
    ]
